import json
import os
from typing import Any

from dotenv import load_dotenv
from groq import Groq

from models import AI_DISCLAIMER
from services.anonymization import build_llm_payload


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# CONFIGURATION
# ============================================================

GROQ_MODEL = os.getenv(
    "GROQ_MODEL",
    "openai/gpt-oss-120b",
)

_groq_client = None


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are an AI assistant supporting a research and
demonstration medical imaging application.

The supplied numerical findings were generated by a
separate medical image segmentation model.

You have NOT examined the original medical image.

Follow these rules:

- Explain only the structured information supplied.
- Never state or imply that a tumor, disease, lesion,
  or abnormality has been clinically confirmed.
- Refer to positive pixels as "segmented pixels",
  "model-positive pixels", or "the segmented region".
- Do not describe segmented pixels as confirmed
  "tumor tissue", "cancer", or confirmed pathology.
- Do not invent diagnoses.
- Do not invent symptoms or clinical history.
- Do not invent anatomical locations.
- Do not provide treatment recommendations.
- Do not treat tumor percentage as confidence.
- Do not treat tumor percentage as tumor volume.
- Do not treat tumor percentage as disease severity.
- The tumor_percentage field represents only the
  percentage of image pixels included in the binary
  segmentation mask at the configured threshold.
- A non-zero segmentation mask does not confirm disease.
- An empty segmentation mask does not rule out disease.
- Do not infer probability, severity, stage, prognosis,
  or diagnostic certainty from the segmentation area.
- Clearly explain uncertainty and limitations.
- State that qualified clinical review is required.
"""


# ============================================================
# RESPONSE STYLES
# ============================================================

STYLE_INSTRUCTIONS = {
    "technical": (
        "Provide a concise technical explanation of the "
        "segmentation model results. Clearly distinguish "
        "model output from clinical interpretation. "
        "Use the terms segmented region or model-positive "
        "pixels rather than confirmed tumor tissue."
    ),

    "simple": (
        "Explain the segmentation results in simple, clear "
        "language suitable for a nontechnical reader. Avoid "
        "definitive diagnostic statements and describe the "
        "result only as model-generated segmentation."
    ),

    "report": (
        "Create a structured draft research report using "
        "the sections Model, Findings, Limitations, and "
        "Review Required. Do not present it as a finalized "
        "clinical radiology report."
    ),
}


# ============================================================
# GROQ CLIENT
# ============================================================

def get_groq_client() -> Groq:

    global _groq_client

    api_key = os.getenv(
        "GROQ_API_KEY"
    )

    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is not configured. "
            "Add it to backend/.env."
        )

    if _groq_client is None:
        _groq_client = Groq(
            api_key=api_key
        )

    return _groq_client


# ============================================================
# GENERATE EXPLANATION
# ============================================================

def generate_groq_explanation(
    analysis: dict[str, Any],
    metadata: dict[str, Any] | None = None,
    style: str = "technical",
) -> dict[str, Any]:

    if style not in STYLE_INSTRUCTIONS:
        raise ValueError(
            f"Unsupported explanation style: {style}"
        )

    payload = build_llm_payload(
        analysis=analysis,
        metadata=metadata,
    )

    if not payload:
        raise ValueError(
            "No approved analysis data was provided."
        )

    client = get_groq_client()

    user_prompt = (
        STYLE_INSTRUCTIONS[style]
        + "\n\n"
        + "Structured segmentation results:\n"
        + json.dumps(
            payload,
            indent=2,
        )
    )

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
        temperature=0.2,
        max_tokens=1200,
    )

    explanation = (
        response.choices[0]
        .message.content
        or ""
    ).strip()

    if not explanation:
        raise RuntimeError(
            "Groq returned an empty response."
        )

    return {
        "success": True,
        "provider": "groq",
        "model": GROQ_MODEL,
        "explanation": explanation,
        "disclaimer": AI_DISCLAIMER,
    }